/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package TodoList;

import vous.bettertodolist.TodoListMainFrame;
import java.awt.Component;
import java.sql.PreparedStatement;
import javax.swing.JButton;
import javax.swing.JOptionPane;

/**
 *
 * @author Logarta
 */
public class TodoListInfo extends javax.swing.JPanel {
    private String receivedMessage;
    private String receivedDate;
    private String receivedStatus;
    public TodoListInfo() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        message = new javax.swing.JLabel();
        due = new javax.swing.JLabel();
        DoneButton = new javax.swing.JButton();

        setBackground(new java.awt.Color(244, 252, 217));
        setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));
        setMaximumSize(new java.awt.Dimension(460, 50));
        setMinimumSize(new java.awt.Dimension(460, 50));
        setPreferredSize(new java.awt.Dimension(460, 50));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        message.setText("Task Here");
        add(message, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 8, 360, -1));

        due.setText("Duedate: ");
        add(due, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 27, 360, -1));

        DoneButton.setBackground(new java.awt.Color(229, 239, 193));
        DoneButton.setText("Done");
        DoneButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DoneButtonActionPerformed(evt);
            }
        });
        add(DoneButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(375, 10, 70, 30));
    }// </editor-fold>//GEN-END:initComponents

    private void DoneButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DoneButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_DoneButtonActionPerformed

    
    public void getInfo(String sentMessage, String sentDate, String sentStatus){
        receivedMessage = sentMessage;
        receivedDate = sentDate;
        receivedStatus = sentStatus;
        
        setInfo();
    }
    
    public void setInfo(){
        message.setText(receivedMessage);
        due.setText("Due: "+receivedDate);
        if (receivedStatus.equals("Overdue")){
            setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255,51,51), 2, true));
        } else if (receivedStatus.equals("Due today")){
            setBorder(new javax.swing.border.LineBorder(new java.awt.Color(50,205,50), 2, true));
        }
    }
    
    public JButton getDone(){
        return DoneButton;
    }
    
    public void changeState(){
        String message = this.message.getText();
        
        try {
            conn con = new conn();
            String sql = "DELETE FROM todolist WHERE todo_message  = ?";
            PreparedStatement st = con.c.prepareStatement(sql);
                
            st.setString(1, message);
            st.executeUpdate();
            con.closeConnection();
        }catch (Exception e){
            JOptionPane.showMessageDialog(null, "An error occured while marking task as done! \n "+e, "Error!", JOptionPane.PLAIN_MESSAGE);        
        }
        TodoListMainFrame refresh = new TodoListMainFrame();
        refresh.setVisible(true);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton DoneButton;
    private javax.swing.JLabel due;
    private javax.swing.JLabel message;
    // End of variables declaration//GEN-END:variables
}
