/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package NotesList;

import java.sql.PreparedStatement;
import javax.swing.JButton;
import javax.swing.JOptionPane;
import vous.bettertodolist.TodoListMainFrame;

/**
 *
 * @author Logarta
 */
public class NotesListNewNote extends javax.swing.JPanel {

    /**
     * Creates new form NotesListNewNote
     */
    public NotesListNewNote() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Title = new javax.swing.JLabel();
        PreferredTitle = new javax.swing.JTextField();
        createButton = new javax.swing.JButton();
        cancelButton = new javax.swing.JButton();

        setBackground(new java.awt.Color(244, 252, 217));
        setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));
        setMaximumSize(new java.awt.Dimension(160, 50));
        setMinimumSize(new java.awt.Dimension(160, 50));
        setPreferredSize(new java.awt.Dimension(160, 50));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Title.setText("Title:");
        add(Title, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 8, -1, -1));
        add(PreferredTitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 8, 110, 16));

        createButton.setBackground(new java.awt.Color(229, 239, 193));
        createButton.setText("Add");
        createButton.setPreferredSize(new java.awt.Dimension(72, 16));
        createButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                createButtonActionPerformed(evt);
            }
        });
        add(createButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 27, 60, -1));

        cancelButton.setBackground(new java.awt.Color(229, 239, 193));
        cancelButton.setText("Cancel");
        cancelButton.setPreferredSize(new java.awt.Dimension(72, 16));
        add(cancelButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(72, 27, 80, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void createButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_createButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_createButtonActionPerformed

    public JButton getCancel(){
        return cancelButton;
    }
    
    public void removePanel(){
        TodoListMainFrame refresh = new TodoListMainFrame();
        refresh.refresh();
    }
    
    public JButton getDone(){
        return createButton;
    }
    public void changeState(){
        String title = this.PreferredTitle.getText();
        try {
            conn con = new conn();
            String sql = "insert into notes(note_title) values(?)";
            PreparedStatement st = con.c.prepareStatement(sql);

            st.setString(1, title);
                
            st.executeUpdate();
            
            st.close();
            con.closeConnection();
            TodoListMainFrame refresh = new TodoListMainFrame();
            refresh.refresh();
        }catch (Exception e){
            JOptionPane.showMessageDialog(null, "An error occured while adding new note! \n "+e, "Error!", JOptionPane.PLAIN_MESSAGE);        
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField PreferredTitle;
    private javax.swing.JLabel Title;
    private javax.swing.JButton cancelButton;
    private javax.swing.JButton createButton;
    // End of variables declaration//GEN-END:variables
}
